CC = cl
CFLAGS = /nologo /TC /W4 /D_CRT_SECURE_NO_WARNINGS
TARGET = demo-win32.exe
VT_TARGET = demo-vt-win32.exe
PROFILE_TARGET = profile-vt-win32.exe
PROFILE_FULL_TARGET = profile-vt-win32-full.exe
TEST_TARGET = test\test_controls.exe

TEST_SRC = test\test_main.c test\test_support.c \
	test\test_listbox.c test\test_edit.c test\test_button.c \
	test\test_window.c test\test_menu.c test\test_statusbar.c \
	test\test_label.c test\test_core.c test\test_checkbox.c \
	test\test_radiobutton.c test\test_combobox.c \
	test\test_scrollbar.c test\test_textarea.c \
	test\test_textmodel.c test\test_editor.c

TUI_SRC = tui.c tui_window.c tui_button.c tui_label.c \
	tui_edit.c tui_listbox.c tui_menu.c tui_statusbar.c \
	tui_checkbox.c tui_radiobutton.c tui_combobox.c tui_scrollbar.c \
	tui_textarea.c tui_textmodel.c tui_editor.c

all: $(TARGET)

$(TARGET): demo.c console_win32.c console_dirty.c $(TUI_SRC) \
	tui.h tui_internal.h console.h console_dirty.h
	$(CC) $(CFLAGS) /Fe$@ demo.c console_win32.c console_dirty.c $(TUI_SRC)

$(VT_TARGET): demo.c console_vt_win32.c console_dirty.c \
	$(TUI_SRC) tui.h tui_internal.h console.h console_dirty.h
	$(CC) $(CFLAGS) /Fe$@ demo.c console_vt_win32.c console_dirty.c $(TUI_SRC)

vt: $(VT_TARGET)

$(PROFILE_TARGET): profile_render.c console_vt_win32.c console_dirty.c console.h \
	console_dirty.h
	$(CC) $(CFLAGS) /Fe$@ profile_render.c console_vt_win32.c console_dirty.c

$(PROFILE_FULL_TARGET): profile_render.c console_vt_win32.c console_dirty.c \
	console.h console_dirty.h
	$(CC) $(CFLAGS) /DTUI_PROFILE_FULL /Fe$@ \
		profile_render.c console_vt_win32.c console_dirty.c

profile: $(PROFILE_TARGET) $(PROFILE_FULL_TARGET)
	$(PROFILE_TARGET)
	$(PROFILE_FULL_TARGET)

$(TEST_TARGET): $(TEST_SRC) $(TUI_SRC) tui.h tui_internal.h console.h \
	test\test_support.h
	$(CC) $(CFLAGS) /I. /Fe$@ $(TEST_SRC) $(TUI_SRC)

test: $(TEST_TARGET)
	$(TEST_TARGET)

clean:
	-del /q $(TARGET) $(VT_TARGET) $(PROFILE_TARGET) \
		$(PROFILE_FULL_TARGET) $(TEST_TARGET) *.obj 2>NUL
